Select 61 VRSTA_DOK,	BROJ_DOK,	GODINA,	201 TIP_DOK,	DATUM_DOK,	DATUM_UNOSA,	USER_ID,	PPARTNER,	REG_BROJ,	1 STATUS,	DATUM_STORNA,
       DATUM_VALUTE,	PREVOZ,	CENA_PREVOZA,	ORG_DEO,1	NACIN_OTPREME,	1 FRANKO,	MESTO_ISPORUKE,	PP_ISPORUKE,	RADNI_NALOG,
       POSLOVNICA,	VAZI_DO,	VRSTA_IZJAVE,	null RABAT,
       SPEC_RABAT,	KASA,	TIP_KASE,	ROK_KASE,	null DPO,	null VALUTA_PLACANJA,	null NACIN_PLACANJA,	BROJ_DOK1
From dokument
where godina = 2009
  and vrsta_Dok in( 61, 11)
  and broj_dok  in (5505 ,9743,9763,9740,9784,9785)
order by datum_dok
