Select VRSTA_DOK,	BROJ_DOK,	GODINA,	TIP_DOK,	DATUM_DOK,	DATUM_UNOSA,	USER_ID,	PPARTNER,	REG_BROJ,	STATUS,	DATUM_STORNA,	
       DATUM_VALUTE,	PREVOZ,	CENA_PREVOZA,	ORG_DEO,	NACIN_OTPREME,	FRANKO,	MESTO_ISPORUKE,	PP_ISPORUKE,	RADNI_NALOG,	POSLOVNICA,	
       VAZI_DO,	VRSTA_IZJAVE,	RABAT,	SPEC_RABAT,	KASA,	TIP_KASE,	ROK_KASE,	DPO,	VALUTA_PLACANJA,	NACIN_PLACANJA,	BROJ_DOK1
from dokument
where godina    = 2009
  and vrsta_Dok = 3
  and broj_dok  = 1752
