SELECT * FROM
(
SELECT 'INV' FIRMA, D.STATUS, D.TIP_DOK, D.DATUM_DOK, D.DATUM_UNOSA, D.BROJ_DOK,  D.ORG_DEO, D.BROJ_DOK1, D.USER_ID
     , (SELECT Z.STATUS FROM ZAVISNI_TROSKOVI Z WHERE Z.GODINA = D.GODINA AND Z.VRSTA_DOK = D.VRSTA_DOK AND Z.BROJ_DOK = D.BROJ_DOK) Z_STAT
FROM DOKUMENT D
WHERE VRSTA_DOK = 3 AND TO_DATE(TO_CHAR(DATUM_UNOSA,'DD.MM.YYYY'),'DD.MM.YYYY') >= TO_DATE('11.11.2009','DD.MM.YYYY')

UNION

SELECT 'RUB' FIRMA, D.STATUS, D.TIP_DOK, D.DATUM_DOK, D.DATUM_UNOSA, D.BROJ_DOK,  D.ORG_DEO, D.BROJ_DOK1, D.USER_ID
     , (SELECT Z.STATUS FROM ZAVISNI_TROSKOVI@RUBIN Z WHERE Z.GODINA = D.GODINA AND Z.VRSTA_DOK = D.VRSTA_DOK AND Z.BROJ_DOK = D.BROJ_DOK) Z_STAT
FROM DOKUMENT@RUBIN D
WHERE VRSTA_DOK = 3 AND TO_DATE(TO_CHAR(DATUM_UNOSA,'DD.MM.YYYY'),'DD.MM.YYYY') >= TO_DATE('11.11.2009','DD.MM.YYYY')

UNION

SELECT 'ALB' FIRMA, D.STATUS, D.TIP_DOK, D.DATUM_DOK, D.DATUM_UNOSA, D.BROJ_DOK,  D.ORG_DEO, D.BROJ_DOK1, D.USER_ID
     , (SELECT Z.STATUS FROM ZAVISNI_TROSKOVI@ALBUS Z WHERE Z.GODINA = D.GODINA AND Z.VRSTA_DOK = D.VRSTA_DOK AND Z.BROJ_DOK = D.BROJ_DOK) Z_STAT
FROM DOKUMENT@ALBUS D
WHERE VRSTA_DOK = 3 AND TO_DATE(TO_CHAR(DATUM_UNOSA,'DD.MM.YYYY'),'DD.MM.YYYY') >= TO_DATE('11.11.2009','DD.MM.YYYY')

UNION

SELECT 'VIT' FIRMA,  D.STATUS, D.TIP_DOK, D.DATUM_DOK, D.DATUM_UNOSA, D.BROJ_DOK,  D.ORG_DEO, D.BROJ_DOK1, D.USER_ID
     , (SELECT Z.STATUS FROM ZAVISNI_TROSKOVI@ALBUS Z WHERE Z.GODINA = D.GODINA AND Z.VRSTA_DOK = D.VRSTA_DOK AND Z.BROJ_DOK = D.BROJ_DOK) Z_STAT
FROM DOKUMENT@VITAL D
WHERE VRSTA_DOK = 3 AND TO_DATE(TO_CHAR(DATUM_UNOSA,'DD.MM.YYYY'),'DD.MM.YYYY') >= TO_DATE('11.11.2009','DD.MM.YYYY')
)
WHERE TIP_DOK = 10
  AND BROJ_DOK1 > 0
