ALTER TABLE VITAL.ZAVISNI_TROSKOVI_FORMULE
 DROP PRIMARY KEY CASCADE;
DROP TABLE VITAL.ZAVISNI_TROSKOVI_FORMULE CASCADE CONSTRAINTS;

CREATE TABLE VITAL.ZAVISNI_TROSKOVI_FORMULE
(
  FORMULA   NUMBER                              NOT NULL,
  VREDNOST  VARCHAR2(100 BYTE)                  NOT NULL,
  OPIS      VARCHAR2(30 BYTE)
)
TABLESPACE DES2
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VITAL.ZAVISNI_TRO_FORMULA_PK ON VITAL.ZAVISNI_TROSKOVI_FORMULE
(FORMULA)
LOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          24K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ZAVISNI_TROSKOVI_FORMULE;

CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI_FORMULE FOR VITAL.ZAVISNI_TROSKOVI_FORMULE;


ALTER TABLE VITAL.ZAVISNI_TROSKOVI_FORMULE ADD (
  CONSTRAINT ZAVISNI_TRO_FORMULA_PK
 PRIMARY KEY
 (FORMULA)
    USING INDEX
    TABLESPACE DES2
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          24K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON VITAL.ZAVISNI_TROSKOVI_FORMULE TO FULL_ACCESS;

GRANT SELECT ON VITAL.ZAVISNI_TROSKOVI_FORMULE TO RESTRICT_ACCESS;
/
ALTER TABLE VITAL.ZAVISNI_TROSKOVI_VRSTE
 DROP PRIMARY KEY CASCADE;
DROP TABLE VITAL.ZAVISNI_TROSKOVI_VRSTE CASCADE CONSTRAINTS;

CREATE TABLE VITAL.ZAVISNI_TROSKOVI_VRSTE
(
  VRSTA_TROSKOVA  VARCHAR2(5 BYTE)              NOT NULL,
  NAZIV           VARCHAR2(30 BYTE)             NOT NULL,
  FORMULA         NUMBER                        NOT NULL,
  OPIS            VARCHAR2(30 BYTE)
)
TABLESPACE DES2
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VITAL.ZAVISNI_TRO_VR_PK ON VITAL.ZAVISNI_TROSKOVI_VRSTE
(VRSTA_TROSKOVA)
LOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          24K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX VITAL.ZAVISNI_TRO_VR_NAZIV_UK ON VITAL.ZAVISNI_TROSKOVI_VRSTE
(NAZIV)
LOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          24K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX VITAL.ZAVISNI_TRO_VR_FK ON VITAL.ZAVISNI_TROSKOVI_VRSTE
(FORMULA)
LOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ZAVISNI_TROSKOVI_VRSTE;

CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI_VRSTE FOR VITAL.ZAVISNI_TROSKOVI_VRSTE;


ALTER TABLE VITAL.ZAVISNI_TROSKOVI_VRSTE ADD (
  CONSTRAINT ZAVISNI_TRO_VR_PK
 PRIMARY KEY
 (VRSTA_TROSKOVA)
    USING INDEX
    TABLESPACE DES2
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          24K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE VITAL.ZAVISNI_TROSKOVI_VRSTE ADD (
  FOREIGN KEY (FORMULA)
 REFERENCES VITAL.ZAVISNI_TROSKOVI_FORMULE (FORMULA));

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON VITAL.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS;

GRANT SELECT ON VITAL.ZAVISNI_TROSKOVI_VRSTE TO RESTRICT_ACCESS;
/
ALTER TABLE VITAL.ZAVISNI_TROSKOVI
 DROP PRIMARY KEY CASCADE;
DROP TABLE VITAL.ZAVISNI_TROSKOVI CASCADE CONSTRAINTS;

CREATE TABLE VITAL.ZAVISNI_TROSKOVI
(
  BROJ_DOK     VARCHAR2(7 BYTE)                 NOT NULL,
  VRSTA_DOK    VARCHAR2(2 BYTE)                 NOT NULL,
  GODINA       NUMBER(4)                        NOT NULL,
  STATUS       NUMBER(2)                        NOT NULL,
  USER_ID      VARCHAR2(30 BYTE)                NOT NULL,
  DATUM_UNOSA  DATE                             NOT NULL
)
TABLESPACE DES2
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.BROJ_DOK IS 'Redni broj zavisnog troska isti je kao broj prijemnice za koju se pravi';

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.VRSTA_DOK IS 'Vrsta zavisnog troska isti je kao broj prijemnice za koju se pravi';

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.GODINA IS 'Godina zavisnog troska isti je kao broj prijemnice za koju se pravi';

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.STATUS IS 'Status zavisnog troska';

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.USER_ID IS 'Korisnik koji je poslednji menjao dokument';

COMMENT ON COLUMN VITAL.ZAVISNI_TROSKOVI.DATUM_UNOSA IS 'Datum zadnje promene dokumenta';


CREATE UNIQUE INDEX VITAL.ZAVISNI_TROSKOVI_PK ON VITAL.ZAVISNI_TROSKOVI
(BROJ_DOK, VRSTA_DOK, GODINA)
NOLOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ZAVISNI_TROSKOVI;

CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI FOR VITAL.ZAVISNI_TROSKOVI;


ALTER TABLE VITAL.ZAVISNI_TROSKOVI ADD (
  CONSTRAINT ZAVISNI_TROSKOVI_PK
 PRIMARY KEY
 (BROJ_DOK, VRSTA_DOK, GODINA)
    USING INDEX
    TABLESPACE DES2
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE VITAL.ZAVISNI_TROSKOVI ADD (
  CONSTRAINT ZAVISNI_TROSKOVI_FK
 FOREIGN KEY (BROJ_DOK, VRSTA_DOK, GODINA)
 REFERENCES VITAL.DOKUMENT (BROJ_DOK,VRSTA_DOK,GODINA));

GRANT DELETE, INSERT, SELECT, UPDATE ON VITAL.ZAVISNI_TROSKOVI TO FULL_ACCESS;

GRANT SELECT ON VITAL.ZAVISNI_TROSKOVI TO RESTRICT_ACCESS;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON VITAL.ZAVISNI_TROSKOVI TO TEST WITH GRANT OPTION;
/
ALTER TABLE VITAL.ZAVISNI_TROSKOVI_STAVKE
 DROP PRIMARY KEY CASCADE;
DROP TABLE VITAL.ZAVISNI_TROSKOVI_STAVKE CASCADE CONSTRAINTS;

CREATE TABLE VITAL.ZAVISNI_TROSKOVI_STAVKE
(
  BROJ_DOK             VARCHAR2(7 BYTE)         NOT NULL,
  VRSTA_DOK            VARCHAR2(3 BYTE)         NOT NULL,
  GODINA               NUMBER                   NOT NULL,
  STAVKA               NUMBER                   NOT NULL,
  VRSTA_TROSKOVA       VARCHAR2(5 BYTE)         NOT NULL,
  DOBAVLJAC_VR_TRO     VARCHAR2(7 BYTE)         NOT NULL,
  DOKUMENT_DOBAVLJACA  VARCHAR2(20 BYTE),
  DOBAVLJAC_DATUM_DOK  DATE,
  VALUTA_PLACANJA      NUMBER,
  IZNOS_TROSKA         NUMBER,
  POREZ_VR_TRO_PROC    NUMBER,
  POREZ_VR_TRO_IZNOS   NUMBER,
  STAVKA_PRIJ          NUMBER,
  PROIZVOD             VARCHAR2(7 BYTE),
  CENA                 NUMBER,
  STARA_CENA           NUMBER
)
TABLESPACE DES2
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VITAL.ZAVISNI_TRO_STAVKE_PK ON VITAL.ZAVISNI_TROSKOVI_STAVKE
(BROJ_DOK, VRSTA_DOK, GODINA, STAVKA)
NOLOGGING
TABLESPACE DES2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ZAVISNI_TROSKOVI_STAVKE;

CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI_STAVKE FOR VITAL.ZAVISNI_TROSKOVI_STAVKE;


ALTER TABLE VITAL.ZAVISNI_TROSKOVI_STAVKE ADD (
  CONSTRAINT ZAVISNI_TRO_STAVKE_PK
 PRIMARY KEY
 (BROJ_DOK, VRSTA_DOK, GODINA, STAVKA)
    USING INDEX
    TABLESPACE DES2
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE VITAL.ZAVISNI_TROSKOVI_STAVKE ADD (
  CONSTRAINT ZAV_TRO_STAV_VR_TRO_FK
 FOREIGN KEY (VRSTA_TROSKOVA)
 REFERENCES VITAL.ZAVISNI_TROSKOVI_VRSTE (VRSTA_TROSKOVA)
    ON DELETE CASCADE,
  CONSTRAINT ZAV_TRO_STAV_DOK_FK
 FOREIGN KEY (BROJ_DOK, VRSTA_DOK, GODINA)
 REFERENCES VITAL.ZAVISNI_TROSKOVI (BROJ_DOK,VRSTA_DOK,GODINA)
    ON DELETE CASCADE);

GRANT DELETE, INSERT, SELECT, UPDATE ON VITAL.ZAVISNI_TROSKOVI_STAVKE TO FULL_ACCESS;

GRANT SELECT ON VITAL.ZAVISNI_TROSKOVI_STAVKE TO RESTRICT_ACCESS;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON VITAL.ZAVISNI_TROSKOVI_STAVKE TO TEST WITH GRANT OPTION;
/
