-- Tabel Prepordajni_procenat
CREATE TABLE INVEJ.PREPRODAJNI_PROCENAT
(
    ORG_DEO  NUMBER      NOT NULL,
    DATUM    DATE        NOT NULL,
    PROCENAT NUMBER(4,2) NOT NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
NOLOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE INVEJ.PREPRODAJNI_PROCENAT
    ADD CONSTRAINT PREPRODAJNI_PROCENAT_PK
    PRIMARY KEY (ORG_DEO,DATUM,PROCENAT)
    USING INDEX TABLESPACE SYSTEM
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(FREELISTS 1
                        FREELIST GROUPS 1
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE INVEJ.PREPRODAJNI_PROCENAT
    ADD CONSTRAINT PREPRODAJNI_PROCENAT_FK
    FOREIGN KEY (ORG_DEO)
    REFERENCES INVEJ.ORGANIZACIONI_DEO (ID)
    ENABLE
/
GRANT DELETE ON INVEJ.PREPRODAJNI_PROCENAT TO FULL_ACCESS
/
GRANT INSERT ON INVEJ.PREPRODAJNI_PROCENAT TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.PREPRODAJNI_PROCENAT TO FULL_ACCESS
/
GRANT UPDATE ON INVEJ.PREPRODAJNI_PROCENAT TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.PREPRODAJNI_PROCENAT TO RESTRICT_ACCESS
/
CREATE PUBLIC SYNONYM PREPRODAJNI_PROCENAT
    FOR INVEJ.PREPRODAJNI_PROCENAT
/
