CREATE TABLE RUBIN.PRODAJNI_CENOVNIK_2
(
    PROIZVOD VARCHAR2(7)  NOT NULL,
    DATUM    DATE         NOT NULL,
    ORG_DEO  NUMBER       NOT NULL,
    STANJE   NUMBER       NOT NULL,
    VALUTA   VARCHAR2(3)  NOT NULL,
    CENA     NUMBER(19,4) NOT NULL,
    RABAT    NUMBER(4,2)      NULL,
    REGRES   NUMBER(4,2)      NULL,
    KOL_CENA NUMBER(10,5) NOT NULL,
    JM_CENA  VARCHAR2(3)  NOT NULL,
    FAK_CENA NUMBER(10,5) NOT NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE RUBIN.PRODAJNI_CENOVNIK_2
    ADD CONSTRAINT PRODAJNI_2_PK
    PRIMARY KEY (DATUM,PROIZVOD,ORG_DEO,VALUTA)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 128K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
CREATE INDEX RUBIN.PRODAJNI_2_PROIZVOD_FK_I
    ON RUBIN.PRODAJNI_CENOVNIK_2(PROIZVOD)
TABLESPACE DES2
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
ALTER TABLE RUBIN.PRODAJNI_CENOVNIK_2
    ADD CONSTRAINT PRODAJNI_2_PROIZVOD_FK
    FOREIGN KEY (PROIZVOD)
    REFERENCES RUBIN.PROIZVOD (SIFRA)
    ENABLE
/
GRANT DELETE ON RUBIN.PRODAJNI_CENOVNIK_2 TO FULL_ACCESS
/
GRANT INSERT ON RUBIN.PRODAJNI_CENOVNIK_2 TO FULL_ACCESS
/
GRANT SELECT ON RUBIN.PRODAJNI_CENOVNIK_2 TO FULL_ACCESS
/
GRANT UPDATE ON RUBIN.PRODAJNI_CENOVNIK_2 TO FULL_ACCESS
/
GRANT SELECT ON RUBIN.PRODAJNI_CENOVNIK_2 TO RESTRICT_ACCESS
/
CREATE PUBLIC SYNONYM PRODAJNI_CENOVNIK_2
    FOR RUBIN.PRODAJNI_CENOVNIK_2
/
----
GRANT SELECT ON RUBIN.PRODAJNI_CENOVNIK_2 TO RESTRICT_ACCESS
/
