declare

Begin
	for nadji in
	        (Select BROJ_DOK,vrsta_dok, GODINA,ORG_dEO,BROJ_DOK1,STATUS, DATUM_UNOSA
	         from dokument
	         where godina = 2013
	           and vrsta_Dok = '3'
	           and datum_dok = '31.12.2013'
			  and user_id = 'VITAL'
			  AND TRUNC(DATUM_UNOSA)='13.01.2014'

	        )
	Loop
	     dbms_output.put_line('Greska  brd ' || nadji.broj_dok);
--			INSERT INTO DEJA_POMOCNA_TAB
--			--(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,POLJE19,POLJE20,POLJE21,POLJE22,POLJE23,POLJE24,POLJE25,POLJE26,POLJE27,POLJE28,POLJE29,POLJE30,POLJE31,POLJE32,POLJE33,POLJE34,POLJE35,POLJE36,POLJE37,POLJE38,POLJE39,POLJE40,POLJE41,POLJE42,POLJE43,POLJE44,POLJE45,POLJE46,POLJE47,POLJE48,POLJE49,POLJE50,POLJE51,POLJE52,POLJE53,POLJE54,POLJE55,POLJE56,POLJE57,POLJE58,POLJE59,POLJE60,POLJE61,POLJE62,POLJE63,POLJE64,POLJE65,POLJE66,POLJE67,POLJE68,POLJE69,POLJE70,POLJE71,POLJE72,POLJE73,POLJE74,POLJE75,POLJE76,POLJE77,POLJE78,POLJE79,POLJE80,POLJE81,
--			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,POLJE19,POLJE20,POLJE21,POLJE22,POLJE23,POLJE24,POLJE25,POLJE26,POLJE27,POLJE28,POLJE29,POLJE30,POLJE31,POLJE32,POLJE33,POLJE34,POLJE35,POLJE36,POLJE37
--			--,POLJE38,POLJE39,POLJE40,POLJE41,POLJE42,POLJE43,POLJE44,POLJE45,POLJE46,POLJE47,POLJE48,POLJE49,POLJE50,POLJE51,POLJE52,POLJE53,POLJE54
--			,POLJE78
--			,POLJE79,POLJE80
--			)
--			SELECT BROJ_DOK,VRSTA_DOK,GODINA,STAVKA,PROIZVOD,LOT_SERIJA,ROK,KOLICINA,JED_MERE,CENA,VALUTA,LOKACIJA,PAKOVANJE,BROJ_KOLETA,K_REZ,K_ROBE,K_OCEK,KONTROLA,FAKTOR,REALIZOVANO,RABAT,POREZ,KOLICINA_KONTROLNA,AKCIZA,TAKSA,CENA1,Z_TROSKOVI,NETO_KG,PROC_VLAGE,PROC_NECISTOCE,HTL,NAPOMENA,UNOS_USERNAME,UNOS_DATUM,UNOS_KOMENTAR,USLUGA,IZVOR_PODATKA,
--			--,TRAJANJE,CENA_JM,NPOLJE1,NPOLJE2,NPOLJE3,NPOLJE4,NPOLJE5,CPOLJE1,CPOLJE2,CPOLJE3,CPOLJE4,CPOLJE5,DPOLJE1,DPOLJE2,DPOLJE3,DPOLJE4,DPOLJE5,
--			'dok_tmp_stavka_dok','1234','BRISANJE PODATAKA'
--			FROM dok_tmp_stavka_dok r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
--			-- Brisanje dok_tmp_stavka_dok
--			delete  dok_tmp_stavka_dok r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------
--			INSERT INTO DEJA_POMOCNA_TAB
--			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE78,POLJE79,POLJE80
--			)
--			SELECT VRSTA_DOK,BROJ_DOK,GODINA,STAVKA,NAPOMENA,UNOS_USERNAME,UNOS_DATUM,UNOS_KOMENTAR
--			,'dok_napomena','1234','BRISANJE PODATAKA'
--			FROM dok_napomena r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
--			-- Brisanje dok_napomena
--			delete  dok_napomena r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------
			-- cuvaj
--			INSERT INTO DEJA_POMOCNA_TAB
--			--(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,POLJE19,POLJE20,POLJE21,POLJE22,POLJE23,POLJE24,POLJE25,POLJE26,POLJE27,POLJE28,POLJE29,POLJE30,POLJE31,POLJE32,POLJE33,POLJE34,POLJE35,POLJE36,POLJE37,POLJE38,POLJE39,POLJE40,POLJE41,POLJE42,POLJE43,POLJE44,POLJE45,POLJE46,POLJE47,POLJE48,POLJE49,POLJE50,POLJE51,POLJE52,POLJE53,POLJE54,POLJE55,POLJE56,POLJE57,POLJE58,POLJE59,POLJE60,POLJE61,POLJE62,POLJE63,POLJE64,POLJE65,POLJE66,POLJE67,POLJE68,POLJE69,POLJE70,POLJE71,POLJE72,POLJE73,POLJE74,POLJE75,POLJE76,POLJE77,POLJE78,POLJE79,POLJE80,POLJE81,
--			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE78,POLJE79,POLJE80
--			)
--			SELECT VRSTA_DOK,BROJ_DOK,GODINA,VRSTA,PPARTNER,NAPOMENA,UNOS_USERNAME,UNOS_DATUM,UNOS_KOMENTAR,
--			'dok_POSLOVNI_PARTNER','1234','BRISANJE PODATAKA'
--			FROM dok_POSLOVNI_PARTNER r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
--			-- Brisanje dok_POSLOVNI_PARTNER
--			delete  dok_POSLOVNI_PARTNER r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------
			-- cuvaj
--			INSERT INTO DEJA_POMOCNA_TAB
--			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,
--			POLJE78,POLJE79,POLJE80
--			)
--			SELECT VRSTA_DOK,BROJ_DOK,GODINA,STAVKA,VRSTA,PPARTNER,PREVOZNIK,PREVOZNIK_MESTO,SREDSTVO,SREDSTVO_REGBR,VOZAC_IME,VOZAC_PREZIME,VOZAC_BRLK,VOZAC_BRLK_MUP,NAPOMENA,UNOS_USERNAME,UNOS_DATUM,UNOS_KOMENTAR,
--			'dok_prevoznik','1234','BRISANJE PODATAKA'
--			FROM dok_prevoznik r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
--			-- Brisanje dok_prevoznik
--			delete  dok_prevoznik r
--			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013
--			;
			---------------------------------------------------------------------------------------------
			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,
			POLJE78,POLJE79,POLJE80
			)
			SELECT VRSTA_DOK,BROJ_DOK,GODINA,STATUS,SLEDECI,USERNAME,DATUM,
			'dok_overa','1234','BRISANJE PODATAKA'
			FROM dok_overa r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			-- Brisanje dok_overa
			delete  dok_overa r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------


			----------------------------------------------------------------------------------------------
			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,
			POLJE78,POLJE79,POLJE80
			)
			SELECT ORG_DEO,PROIZVOD,DATUM,DATUM_UNOSA,KOLICINA,CENA,PRETHODNA_KOLICINA,PRETHODNA_CENA,VRSTA_DOK,BROJ_DOK,GODINA,STAVKA_DOK,
			'prosecni_cenovnik','1234','BRISANJE PODATAKA'
			FROM prosecni_cenovnik r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			-- Brisanje stavka_dok
			delete  prosecni_cenovnik r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;


			----------------------------------------------------------------------------------------------
			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,POLJE19,POLJE20,POLJE21,POLJE22,POLJE23,POLJE24,POLJE25,POLJE26,POLJE27,POLJE28,POLJE29,POLJE30,POLJE31,POLJE32,POLJE33,POLJE34,POLJE35,POLJE36,POLJE37,POLJE38,POLJE39,POLJE40,POLJE41,POLJE42,POLJE43,POLJE44,POLJE45,POLJE46,POLJE47,POLJE48,POLJE49,POLJE50,POLJE51,POLJE52,POLJE53,POLJE54,
			POLJE78,POLJE79,POLJE80
			)
			SELECT BROJ_DOK,VRSTA_DOK,GODINA,STAVKA,PROIZVOD,LOT_SERIJA,ROK,KOLICINA,JED_MERE,CENA,VALUTA,LOKACIJA,PAKOVANJE,BROJ_KOLETA,K_REZ,K_ROBE,K_OCEK,KONTROLA,FAKTOR,REALIZOVANO,RABAT,POREZ,KOLICINA_KONTROLNA,AKCIZA,TAKSA,CENA1,Z_TROSKOVI,NETO_KG,PROC_VLAGE,PROC_NECISTOCE,HTL,NAPOMENA,UNOS_USERNAME,UNOS_DATUM,UNOS_KOMENTAR,USLUGA,IZVOR_PODATKA,TRAJANJE,CENA_JM,NPOLJE1,NPOLJE2,NPOLJE3,NPOLJE4,NPOLJE5,CPOLJE1,CPOLJE2,CPOLJE3,CPOLJE4,CPOLJE5,DPOLJE1,DPOLJE2,DPOLJE3,DPOLJE4,DPOLJE5,
			'stavka_dok','1234','BRISANJE PODATAKA'
			FROM stavka_dok r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			-- Brisanje stavka_dok
			delete  stavka_dok r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------
			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,
			POLJE78,POLJE79,POLJE80
			)
			SELECT BROJ_DOK,VRSTA_DOK,GODINA,STAVKA,KOMENTAR,
			'komentar','1234','BRISANJE PODATAKA'
			FROM komentar r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			-- Brisanje komentar
			delete  komentar r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
			---------------------------------------------------------------------------------------------
			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,
			POLJE78,POLJE79,POLJE80
			)
			SELECT BROJ_DOK,VRSTA_DOK,GODINA,ZA_BROJ_DOK,ZA_VRSTA_DOK,ZA_GODINA,
			'VEZNI_DOK','1234','BRISANJE PODATAKA'
			FROM VEZNI_DOK r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;

			-- Brisanje dokument
			delete  zavisni_troskovi r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;

			-- cuvaj
			INSERT INTO DEJA_POMOCNA_TAB
			(POLJE1,POLJE2,POLJE3,POLJE4,POLJE5,POLJE6,POLJE7,POLJE8,POLJE9,POLJE10,POLJE11,POLJE12,POLJE13,POLJE14,POLJE15,POLJE16,POLJE17,POLJE18,POLJE19,POLJE20,POLJE21,POLJE22,POLJE23,POLJE24,POLJE25,POLJE26,POLJE27,POLJE28,POLJE29,POLJE30,POLJE31,POLJE32,POLJE33,POLJE34,POLJE35,POLJE36,POLJE37,POLJE38,POLJE39,POLJE40,POLJE41,POLJE42,POLJE43,POLJE44,POLJE45,POLJE46,POLJE47,POLJE48,POLJE49,POLJE50,POLJE51,POLJE52,
			POLJE78,POLJE79,POLJE80
			)
			SELECT VRSTA_DOK,BROJ_DOK,GODINA,TIP_DOK,DATUM_DOK,DATUM_UNOSA,USER_ID,PPARTNER,REG_BROJ,STATUS,DATUM_STORNA,DATUM_VALUTE,PREVOZ,CENA_PREVOZA,ORG_DEO,NACIN_OTPREME,FRANKO,MESTO_ISPORUKE,PP_ISPORUKE,RADNI_NALOG,POSLOVNICA,VAZI_DO,VRSTA_IZJAVE,RABAT,SPEC_RABAT,KASA,TIP_KASE,ROK_KASE,DPO,VALUTA_PLACANJA,NACIN_PLACANJA,BROJ_DOK1,SKLOP,JM_UG,IZNOS_UG,CENA_UG_JM,NPOLJE1,NPOLJE2,NPOLJE3,NPOLJE4,NPOLJE5,CPOLJE1,CPOLJE2,CPOLJE3,CPOLJE4,CPOLJE5,DPOLJE1,DPOLJE2,DPOLJE3,DPOLJE4,DPOLJE5,DATUM_IZVORNOG_DOK,
			'DOKUMENT','1234','BRISANJE PODATAKA'
			FROM DOKUMENT r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;


			-- Brisanje dokument
			delete  dokument r
			where BROJ_DOK IN (nadji.broj_dok ) AND VRSTA_DOK=nadji.vrsta_dok AND godina = 2013;
	End Loop;
end;
