----------------------------------------------------------------------------------
-- tabela ZAVISNI_TROSKOVI_VRSTE
CREATE TABLE INVEJ.ZAVISNI_TROSKOVI_VRSTE
(
    VRSTA_TROSKOVA VARCHAR2(5)  NOT NULL,
    NAZIV          VARCHAR2(30) NOT NULL,
    FORMULA        NUMBER       NOT NULL,
    OPIS           VARCHAR2(30)     NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE INVEJ.ZAVISNI_TROSKOVI_VRSTE
    ADD CONSTRAINT ZAVISNI_TRO_VR_PK
    PRIMARY KEY (VRSTA_TROSKOVA)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 24K
                        BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
CREATE UNIQUE INDEX INVEJ.ZAVISNI_TRO_VR_NAZIV_UK
    ON INVEJ.ZAVISNI_TROSKOVI_VRSTE(NAZIV)
TABLESPACE DES2
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
CREATE INDEX INVEJ.ZAVISNI_TRO_VR_FK
    ON INVEJ.ZAVISNI_TROSKOVI_VRSTE(FORMULA)
TABLESPACE DES2
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
ALTER TABLE INVEJ.ZAVISNI_TROSKOVI_VRSTE
    ADD CONSTRAINT SYS_C009827
    FOREIGN KEY (FORMULA)
    REFERENCES INVEJ.ZAVISNI_TROSKOVI_FORMULE (FORMULA)
    ENABLE
/
GRANT ALTER ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT DEBUG ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT DELETE ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT FLASHBACK ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT INSERT ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT ON COMMIT REFRESH ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT QUERY REWRITE ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT UPDATE ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO RESTRICT_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_VRSTE TO ZA_PROGRAMERE
/
CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI_VRSTE
    FOR INVEJ.ZAVISNI_TROSKOVI_VRSTE