-- tabela ZAVISNI_TROSKOVI_STAVKE
CREATE TABLE INVEJ.ZAVISNI_TROSKOVI_STAVKE
(
    BROJ_DOK            VARCHAR2(7)  NOT NULL,
    VRSTA_DOK           VARCHAR2(3)  NOT NULL,
    GODINA              NUMBER       NOT NULL,
    STAVKA              NUMBER       NOT NULL,
    VRSTA_TROSKOVA      VARCHAR2(5)  NOT NULL,
    DOBAVLJAC_VR_TRO    VARCHAR2(7)  NOT NULL,
    DOKUMENT_DOBAVLJACA VARCHAR2(20)     NULL,
    DOBAVLJAC_DATUM_DOK DATE             NULL,
    VALUTA_PLACANJA     NUMBER           NULL,
    IZNOS_TROSKA        NUMBER           NULL,
    POREZ_VR_TRO_PROC   NUMBER           NULL,
    POREZ_VR_TRO_IZNOS  NUMBER           NULL,
    STAVKA_PRIJ         NUMBER           NULL,
    PROIZVOD            VARCHAR2(7)      NULL,
    CENA                NUMBER           NULL,
    STARA_CENA          NUMBER           NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
NOLOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE INVEJ.ZAVISNI_TROSKOVI_STAVKE
    ADD CONSTRAINT ZAVISNI_TRO_STAVKE_PK
    PRIMARY KEY (BROJ_DOK,VRSTA_DOK,GODINA,STAVKA)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    NOLOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE INVEJ.ZAVISNI_TROSKOVI_STAVKE
    ADD CONSTRAINT ZAV_TRO_STAV_VR_TRO_FK
    FOREIGN KEY (VRSTA_TROSKOVA)
    REFERENCES INVEJ.ZAVISNI_TROSKOVI_VRSTE (VRSTA_TROSKOVA)
    ON DELETE CASCADE
    ENABLE
/
ALTER TABLE INVEJ.ZAVISNI_TROSKOVI_STAVKE
    ADD CONSTRAINT ZAV_TRO_STAV_DOK_FK
    FOREIGN KEY (BROJ_DOK,VRSTA_DOK,GODINA)
    REFERENCES INVEJ.ZAVISNI_TROSKOVI (BROJ_DOK,VRSTA_DOK,GODINA)
    ON DELETE CASCADE
    ENABLE
/
GRANT DELETE ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO FULL_ACCESS
/
GRANT INSERT ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO FULL_ACCESS
/
GRANT UPDATE ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO RESTRICT_ACCESS
/
GRANT SELECT ON INVEJ.ZAVISNI_TROSKOVI_STAVKE TO ZA_PROGRAMERE
/
CREATE PUBLIC SYNONYM ZAVISNI_TROSKOVI_STAVKE
    FOR INVEJ.ZAVISNI_TROSKOVI_STAVKE
/