--SELECT SD.ROWID ,SD.VRSTA_DOK, BROJ_DOK ,SD.CENA , SD.CENA1
--FROM STAVKA_DOK SD
UPDATE STAVKA_DOK SD
SET SD.CENA1 = SD.CENA
WHERE SD.GODINA = 2006
AND SD.PROIZVOD = 257
AND SD.CENA <> SD.CENA1
AND SD.VALUTA = 'YUD'
AND SD.CENA IS NOT NULL
