

--SELECT * FROM POPIS WHERE GODINA = 2012  AND POPISNA_LISTA>4;
--
--
--delete popis WHERE GODINA = 2012  AND POPISNA_LISTA>4;
--
--update SEKVENCA set stanje = 4 WHERE GODINA = 2012 and NAZIV='POPISNA_LISTA'
