select
*
from

STAVKA_POPISA SP--,
--POPIS SP
WHERE SP.POPISNA_LISTA = 19
  AND SP.GODINA = 2011
--      P.datum = to_date('19.09.2009','dd.mm.yyyy')
--  AND P.POPISNA_LISTA = SP.POPISNA_LISTA
--  AND P.GODINA = SP.GODINA
  AND PROIZVOD = 7536
ORDER BY TO_NUMBER(PROIZVOD)
--ORDER BY STAVKA
