SELECT GODINA, VRSTA_DOK, BROJ_DOK, za_vrsta_Dok, COUNT(*)--, ZA_GODINA, ZA_VRSTA_DOK
FROM VEZNI_DOK
WHERE GODINA = 2012
--  AND VRSTA_DOK =
  AND (GODINA, VRSTA_DOK, BROJ_DOK)
       IN (SELECT GODINA, VRSTA_DOK, BROJ_DOK FROM DOKUMENT D
           WHERE D.GODINA    = 2012
--             AND D.VRSTA_DOK = 73
--             AND D.ORG_DEO = 113
--             AND D.DATUM_DOK = TO_DATE('15.04.2009','DD.MM.YYYY')
           )
GROUP BY GODINA, VRSTA_DOK, BROJ_DOK, za_vrsta_Dok--, ZA_GODINA, ZA_VRSTA_DOK
HAVING COUNT(*)>1
ORDER BY GODINA, TO_NUMBER(BROJ_DOK), ZA_VRSTA_DOK
