select Distinct RN.BR_SASTAVNICE
from STAVKA_RAD_NAL RN , VEZNI_DOK VD
Where RN.GODINA = 2008
  AND RN.BR_SASTAVNICE IS NOT NULL
  AND RN.GODINA            = VD.GODINA
  AND RN.BR_RADNOG_NALOGA  = VD.BROJ_DOK
  AND VD.VRSTA_dOK = 29

ORDER BY TO_NUMBER(RN.BR_SASTAVNICE)
