select
-- DISTINCT SD.BROJ_DOK
SD.ROWID,
SD.BROJ_DOK,SD.VRSTA_DOK,SD.GODINA,SD.STAVKA,SD.PROIZVOD, SD.CENA1
,1 NPOLJE1_1
, SD.NPOLJE1
, SD.NPOLJE2,SD.NPOLJE3, SD.NPOLJE4,SD.NPOLJE5

, SD1.NPOLJE1
, SD1.NPOLJE2,SD1.NPOLJE4,SD1.NPOLJE5
--, VD.*
from stavka_Dok SD
, (SELECT * FROM VEZNI_DOK WHERE ZA_VRSTA_dOK IN ('11','13') ) VD
, STAVKA_DOK SD1
where SD.godina = 2014
  and SD.vrsta_dok='89'
--  and TO_NUMBER(broj_dok)>768
AND NVL(SD.CENA1,0) = 0

AND VD.GODINA = SD.GODINA
AND VD.VRSTA_dOK=SD.VRSTA_DOK
AND VD.BROJ_DOK=SD.BROJ_DOK

AND SD1.GODINA = VD.ZA_GODINA
AND SD1.VRSTA_dOK=VD.ZA_VRSTA_DOK
AND SD1.BROJ_DOK=VD.ZA_BROJ_DOK
AND SD1.STAVKA = SD.STAVKA
order by SD.BROJ_DOK
--, stavka
