Select 
       LOG_ID, USER_ID, DATUM_PROMENE, TIP_TRANSAKCIJE
     , PROIZVOD_OLD, PROIZVOD_NEW
     , CENA_OLD, CENA_NEW
     , KOL_CENA_OLD, KOL_CENA_NEW
     , ROUND(CENA_OLD/KOL_CENA_OLD,4) CENA_O
     , ROUND(CENA_NEW/KOL_CENA_NEW,4) CENA_N
     
from PRODAJNI_CENOVNIK_LOG
WHERE
--PROIZVOD_OLD = '114124'
PROIZVOD_OLD = '113416'
OR
PROIZVOD_NEW = '113416'
ORDER BY DATUM_PROMENE DESC
