SELECT
       PC.ROWID
     , D.BROJ_DOK1
     , D.DATUM_UNOSA
     , PC.ORG_DEO,PC.PROIZVOD,PC.DATUM,PC.DATUM_UNOSA
     , PC.KOLICINA,PC.CENA,PC.PRETHODNA_KOLICINA,PC.PRETHODNA_CENA
     , PC.VRSTA_DOK,PC.BROJ_DOK,PC.GODINA,PC.STAVKA_DOK

, SD.PROIZVOD PRO
, SD.CENA1
FROM PROSECNI_CENOVNIK PC
   , STAVKA_DOK SD
   , DOKUMENT D
WHERE
      PC.ORG_DEO
= 1511
--BETWEEN 1400 AND 1520

--      PC.PROIZVOD = '211110'
  AND D.ORG_DEO=PC.ORG_DEO

  AND D.GODINA = PC.GODINA
  AND D.VRSTA_DOK = PC.VRSTA_DOK
  AND D.BROJ_DOK = PC.BROJ_DOK

  AND SD.GODINA = D.GODINA
  AND SD.VRSTA_DOK = D.VRSTA_DOK
  AND SD.BROJ_DOK = D.BROJ_DOK

  AND SD.STAVKA = PC.STAVKA_DOK
ORDER BY D.DATUM_dOK,D.DATUM_UNOSA
-- DESC

